import type { Metadata } from "next";
import { LegalDocument, type LegalItem } from "@/components/legal-document";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for SafeStop by Ravenna Technologies LLC.",
  alternates: { canonical: "https://safestop.global/privacy" },
};

const items: LegalItem[] = [
  { type: "paragraph", text: "SafeStop is operated by Ravenna Technologies LLC." },
  { type: "paragraph", text: "This Privacy Policy explains how we collect, use, disclose, and protect information when you use the SafeStop mobile application, website, and related services." },
  { type: "heading", text: "1. Adult-Use Service" },
  { type: "paragraph", text: "SafeStop is intended for use by adults, including parents, guardians, and authorized caregivers." },
  { type: "paragraph", text: "Children are not intended users of SafeStop and do not create or manage SafeStop accounts." },
  { type: "paragraph", text: "Information relating to children is provided by adults for transportation-awareness and caregiver-coordination purposes." },
  { type: "heading", text: "2. Information We Collect" },
  { type: "heading", text: "Account Information" },
  { type: "paragraph", text: "We may collect:" },
  { type: "listItem", text: "Name" },
  { type: "listItem", text: "Email address" },
  { type: "listItem", text: "Phone number" },
  { type: "listItem", text: "Profile photo" },
  { type: "listItem", text: "Authentication identifiers" },
  { type: "listItem", text: "Login provider information" },
  { type: "heading", text: "Child Profile Information" },
  { type: "paragraph", text: "Users may voluntarily provide:" },
  { type: "listItem", text: "Child names" },
  { type: "listItem", text: "Child nicknames" },
  { type: "listItem", text: "Child photographs" },
  { type: "listItem", text: "Transportation-related information" },
  { type: "listItem", text: "Authorized user relationships connected to a child profile" },
  { type: "paragraph", text: "Users represent that they have authority to provide child-related information." },
  { type: "heading", text: "Location Information" },
  { type: "paragraph", text: "With your permission, SafeStop may collect:" },
  { type: "listItem", text: "Precise location" },
  { type: "listItem", text: "Foreground location data" },
  { type: "listItem", text: "Background location data" },
  { type: "listItem", text: "GPS coordinates" },
  { type: "listItem", text: "Device movement information" },
  { type: "listItem", text: "Trip-related location events" },
  { type: "listItem", text: "Location-based session activity" },
  { type: "paragraph", text: "Location information is used to provide transportation-awareness, reminder, tracking, and notification features." },
  { type: "heading", text: "Trip and Session Information" },
  { type: "paragraph", text: "We may collect:" },
  { type: "listItem", text: "Check-in and checkout activity" },
  { type: "listItem", text: "Trip start and end times" },
  { type: "listItem", text: "Session history" },
  { type: "listItem", text: "Alert events" },
  { type: "listItem", text: "Notification events" },
  { type: "listItem", text: "Driver and tracker relationships for a session" },
  { type: "listItem", text: "Emergency checkout activity, if applicable" },
  { type: "heading", text: "Photographs" },
  { type: "paragraph", text: "Users may upload photographs as part of session checkout records." },
  { type: "heading", text: "Notification Information" },
  { type: "paragraph", text: "We may collect:" },
  { type: "listItem", text: "Push notification tokens" },
  { type: "listItem", text: "Notification delivery events" },
  { type: "listItem", text: "Notification interaction data" },
  { type: "listItem", text: "Device tokens used to deliver alerts and reminders" },
  { type: "heading", text: "Device Information" },
  { type: "paragraph", text: "We may collect:" },
  { type: "listItem", text: "Device identifiers" },
  { type: "listItem", text: "Device type" },
  { type: "listItem", text: "Device model" },
  { type: "listItem", text: "Operating system version" },
  { type: "listItem", text: "App version" },
  { type: "listItem", text: "Network information" },
  { type: "listItem", text: "Device settings relevant to app functionality" },
  { type: "heading", text: "Diagnostics and Usage Information" },
  { type: "paragraph", text: "We may collect:" },
  { type: "listItem", text: "Crash reports" },
  { type: "listItem", text: "Error logs" },
  { type: "listItem", text: "Performance metrics" },
  { type: "listItem", text: "Diagnostic events" },
  { type: "listItem", text: "Application usage analytics" },
  { type: "listItem", text: "Feature usage" },
  { type: "listItem", text: "Account activity" },
  { type: "heading", text: "Payment and Subscription Information" },
  { type: "paragraph", text: "Paid subscriptions are processed through Apple’s App Store." },
  { type: "paragraph", text: "We do not directly collect or store full payment card information." },
  { type: "paragraph", text: "We may receive subscription status information from Apple, such as whether a subscription is active, expired, renewed, canceled, or eligible for access to paid features." },
  { type: "heading", text: "3. How We Use Information" },
  { type: "paragraph", text: "We use information to:" },
  { type: "listItem", text: "Operate SafeStop" },
  { type: "listItem", text: "Provide reminders and notifications" },
  { type: "listItem", text: "Support caregiver coordination" },
  { type: "listItem", text: "Provide location-based trip awareness features" },
  { type: "listItem", text: "Authenticate users" },
  { type: "listItem", text: "Manage subscriptions" },
  { type: "listItem", text: "Improve app performance" },
  { type: "listItem", text: "Diagnose bugs and technical issues" },
  { type: "listItem", text: "Detect abuse, fraud, or misuse" },
  { type: "listItem", text: "Maintain safety-related records" },
  { type: "listItem", text: "Comply with legal obligations" },
  { type: "listItem", text: "Enforce our Terms of Service" },
  { type: "heading", text: "4. Sharing Information" },
  { type: "heading", text: "With Authorized Users" },
  { type: "paragraph", text: "Information may be shared with users you authorize, including:" },
  { type: "listItem", text: "Partners" },
  { type: "listItem", text: "Co-parents" },
  { type: "listItem", text: "Drivers" },
  { type: "listItem", text: "Trackers" },
  { type: "listItem", text: "Administrators" },
  { type: "listItem", text: "Authorized caregivers" },
  { type: "paragraph", text: "The information shared may include child profiles, trip activity, session status, location-related session information, checkout records, and notifications, depending on the access granted." },
  { type: "heading", text: "With Service Providers" },
  { type: "paragraph", text: "We may share information with third-party service providers that help us operate, maintain, improve, secure, and support SafeStop." },
  { type: "paragraph", text: "These providers may support services including:" },
  { type: "listItem", text: "Authentication" },
  { type: "listItem", text: "Cloud hosting and infrastructure" },
  { type: "listItem", text: "Messaging and communications" },
  { type: "listItem", text: "Location and mapping services" },
  { type: "listItem", text: "Analytics and diagnostics" },
  { type: "listItem", text: "Payment processing" },
  { type: "listItem", text: "Subscription management" },
  { type: "listItem", text: "Advertising" },
  { type: "listItem", text: "Customer support" },
  { type: "listItem", text: "Security and fraud prevention" },
  { type: "paragraph", text: "Examples of providers we may use include Apple, Google, Supabase, Twilio, Stripe, AdMob, and similar service providers. These providers may change over time as our services evolve." },
  { type: "paragraph", text: "These providers may process information on our behalf or according to their own terms and privacy policies." },
  { type: "heading", text: "Legal Requirements" },
  { type: "paragraph", text: "We may disclose information if required by law, legal process, or governmental request, or if we believe disclosure is necessary to protect rights, safety, security, or property." },
  { type: "heading", text: "5. Advertising" },
  { type: "paragraph", text: "SafeStop may display advertisements through third-party advertising providers, including Google AdMob." },
  { type: "paragraph", text: "Advertising providers may collect certain information in accordance with their own privacy policies." },
  { type: "paragraph", text: "Users may be presented with consent options where required by applicable law." },
  { type: "heading", text: "6. Data Retention" },
  { type: "paragraph", text: "We retain information for as long as necessary to:" },
  { type: "listItem", text: "Provide SafeStop" },
  { type: "listItem", text: "Maintain user accounts" },
  { type: "listItem", text: "Support app functionality" },
  { type: "listItem", text: "Meet legal obligations" },
  { type: "listItem", text: "Resolve disputes" },
  { type: "listItem", text: "Enforce agreements" },
  { type: "listItem", text: "Prevent fraud or abuse" },
  { type: "listItem", text: "Maintain safety, security, and audit records" },
  { type: "heading", text: "7. Account Deletion" },
  { type: "paragraph", text: "Users may delete their account and related data directly within the SafeStop application by navigating to:" },
  { type: "paragraph", text: "Settings → Privacy → Delete Account and Data" },
  { type: "paragraph", text: "The Delete Account and Data button deletes your account, children, trips, partner connections, and device tokens." },
  { type: "paragraph", text: "This action cannot be undone." },
  { type: "paragraph", text: "After deletion, certain limited records may be retained where required by law, security requirements, fraud prevention, dispute resolution, backup retention, or other legitimate business purposes." },
  { type: "heading", text: "8. Children’s Privacy" },
  { type: "paragraph", text: "SafeStop is intended for use by adults." },
  { type: "paragraph", text: "Children are not intended users of the application and do not create accounts directly." },
  { type: "paragraph", text: "Information regarding children is provided by parents, guardians, or authorized adult caregivers." },
  { type: "paragraph", text: "If you believe information has been collected improperly regarding a child, contact us at yehuda@safestop.global." },
  { type: "heading", text: "9. Security" },
  { type: "paragraph", text: "We implement reasonable administrative, technical, and organizational safeguards designed to protect information." },
  { type: "paragraph", text: "However, no security system can guarantee absolute security." },
  { type: "heading", text: "10. International Transfers" },
  { type: "paragraph", text: "Information may be processed and stored in jurisdictions outside your state or country." },
  { type: "heading", text: "11. Your Rights" },
  { type: "paragraph", text: "Depending on your location, you may have rights to:" },
  { type: "listItem", text: "Access your information" },
  { type: "listItem", text: "Correct your information" },
  { type: "listItem", text: "Delete your information" },
  { type: "listItem", text: "Restrict processing" },
  { type: "listItem", text: "Request data portability" },
  { type: "listItem", text: "Object to certain processing" },
  { type: "paragraph", text: "To exercise rights not available directly in the app, contact yehuda@safestop.global." },
  { type: "heading", text: "12. Third-Party Services" },
  { type: "paragraph", text: "SafeStop may interact with third-party platforms and services, including Apple, Google, Supabase, Twilio, Stripe, AdMob, analytics providers, cloud hosting providers, and mapping or location service providers." },
  { type: "paragraph", text: "Use of third-party services may be governed by their own terms and privacy policies." },
  { type: "heading", text: "13. Changes to this Privacy Policy" },
  { type: "paragraph", text: "We may update this Privacy Policy from time to time." },
  { type: "paragraph", text: "Continued use of SafeStop after updates means you accept the updated Privacy Policy." },
  { type: "heading", text: "14. Contact Information" },
  { type: "paragraph", text: "Ravenna Technologies LLC" },
  { type: "paragraph", text: "Email: yehuda@safestop.global" },
  { type: "paragraph", text: "Website: https://safestop.global" },
];

export default function PrivacyPage() {
  return (
    <LegalPage title="SafeStop Privacy Policy" effectiveDate="Effective Date: June 22, 2026">
      <LegalDocument items={items} />
    </LegalPage>
  );
}
