import type { Metadata } from "next";
import { LegalDocument, type LegalItem } from "@/components/legal-document";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for SafeStop by Ravenna Technologies LLC.",
  alternates: { canonical: "https://safestop.global/terms" },
};

const items: LegalItem[] = [
  { type: "paragraph", text: "Welcome to SafeStop. These Terms of Service govern your use of the SafeStop mobile application, website, and related services operated by Ravenna Technologies LLC." },
  { type: "paragraph", text: "By downloading, installing, accessing, or using SafeStop, you agree to these Terms. If you do not agree, do not use SafeStop." },
  { type: "heading", text: "1. User Eligibility" },
  { type: "paragraph", text: "You must be at least eighteen (18) years old to create, maintain, or use a SafeStop account." },
  { type: "paragraph", text: "By using SafeStop, you represent and warrant that:" },
  { type: "listItem", text: "You are at least 18 years old." },
  { type: "listItem", text: "You have legal authority to enter into these Terms." },
  { type: "listItem", text: "You have authority to provide information regarding any child profiles you create or manage." },
  { type: "listItem", text: "You will comply with all applicable laws and regulations." },
  { type: "heading", text: "2. Important Safety Disclaimer" },
  { type: "paragraph", text: "SAFESTOP IS NOT A SAFETY DEVICE." },
  { type: "paragraph", text: "SAFESTOP IS NOT A CHILD MONITORING DEVICE." },
  { type: "paragraph", text: "SAFESTOP IS NOT AN EMERGENCY RESPONSE SERVICE." },
  { type: "paragraph", text: "SAFESTOP IS NOT A LIFE-SAVING DEVICE." },
  { type: "paragraph", text: "SAFESTOP IS NOT A SUBSTITUTE FOR PROPER SUPERVISION, ATTENTION, OR CARE OF A CHILD." },
  { type: "paragraph", text: "SafeStop is intended to encourage caregiver awareness and provide transportation-related reminders. SafeStop is not designed, marketed, or intended to serve as a child safety device, child restraint system, vehicle safety system, emergency alert service, or life-saving technology." },
  { type: "paragraph", text: "Users must always exercise independent judgment and maintain active supervision of children regardless of whether SafeStop is being used." },
  { type: "paragraph", text: "The safety, supervision, transportation, and wellbeing of children remain solely the responsibility of the responsible adult at all times." },
  { type: "heading", text: "3. Emergency Services Disclaimer" },
  { type: "paragraph", text: "SafeStop does not contact:" },
  { type: "listItem", text: "911" },
  { type: "listItem", text: "Emergency responders" },
  { type: "listItem", text: "Police departments" },
  { type: "listItem", text: "Fire departments" },
  { type: "listItem", text: "Ambulance services" },
  { type: "listItem", text: "Schools" },
  { type: "listItem", text: "Transportation providers" },
  { type: "listItem", text: "Medical personnel" },
  { type: "listItem", text: "Government agencies" },
  { type: "paragraph", text: "SafeStop does not dispatch assistance or emergency resources of any kind." },
  { type: "paragraph", text: "If an emergency exists or is suspected, users must immediately contact the appropriate emergency services directly." },
  { type: "heading", text: "4. No Guarantee of Protection" },
  { type: "paragraph", text: "SafeStop makes no guarantee, warranty, or representation that use of the application will:" },
  { type: "listItem", text: "Prevent injury" },
  { type: "listItem", text: "Prevent death" },
  { type: "listItem", text: "Prevent forgotten-child incidents" },
  { type: "listItem", text: "Prevent accidents" },
  { type: "listItem", text: "Prevent emergencies" },
  { type: "listItem", text: "Prevent property damage" },
  { type: "listItem", text: "Detect every situation" },
  { type: "listItem", text: "Deliver every notification" },
  { type: "listItem", text: "Provide accurate location information" },
  { type: "listItem", text: "Ensure any child’s safety" },
  { type: "paragraph", text: "No feature of SafeStop should ever be relied upon as the sole method of protecting a child." },
  { type: "heading", text: "5. Technology Limitations and Notification Failures" },
  { type: "paragraph", text: "Users acknowledge that SafeStop relies upon technology that may fail or operate imperfectly." },
  { type: "paragraph", text: "Notifications, alerts, reminders, location updates, photographs, tracking information, and other services may be delayed, interrupted, suppressed, blocked, throttled, duplicated, modified, lost, or never delivered due to factors including:" },
  { type: "listItem", text: "Software bugs" },
  { type: "listItem", text: "System defects" },
  { type: "listItem", text: "Hardware failures" },
  { type: "listItem", text: "Operating system limitations" },
  { type: "listItem", text: "Apple system behavior" },
  { type: "listItem", text: "Device settings" },
  { type: "listItem", text: "Focus modes" },
  { type: "listItem", text: "Silent modes" },
  { type: "listItem", text: "Battery-saving modes" },
  { type: "listItem", text: "Low Power Mode" },
  { type: "listItem", text: "GPS inaccuracies" },
  { type: "listItem", text: "Cellular network interruptions" },
  { type: "listItem", text: "Internet outages" },
  { type: "listItem", text: "Cloud service failures" },
  { type: "listItem", text: "Third-party provider failures" },
  { type: "listItem", text: "User error" },
  { type: "listItem", text: "Unexpected technical defects" },
  { type: "paragraph", text: "SafeStop does not guarantee uninterrupted, timely, accurate, or error-free operation." },
  { type: "heading", text: "6. User Responsibilities" },
  { type: "paragraph", text: "Users are solely responsible for:" },
  { type: "listItem", text: "Supervising children and dependents" },
  { type: "listItem", text: "Confirming vehicle occupancy" },
  { type: "listItem", text: "Confirming child pickup and drop-off" },
  { type: "listItem", text: "Keeping devices charged" },
  { type: "listItem", text: "Maintaining internet or cellular connectivity when available" },
  { type: "listItem", text: "Allowing required permissions" },
  { type: "listItem", text: "Following all applicable laws" },
  { type: "listItem", text: "Exercising independent judgment" },
  { type: "listItem", text: "Maintaining awareness of their surroundings" },
  { type: "listItem", text: "Ensuring authorized users are appropriate and trustworthy" },
  { type: "paragraph", text: "Users shall not rely solely on SafeStop when making decisions involving child safety." },
  { type: "heading", text: "7. Accounts, Children, and Authorized Users" },
  { type: "paragraph", text: "Users may create child profiles and authorize other users, including partners, drivers, trackers, administrators, or caregivers." },
  { type: "paragraph", text: "The account owner or authorized administrator is responsible for:" },
  { type: "listItem", text: "Obtaining any required permissions" },
  { type: "listItem", text: "Ensuring the accuracy of information" },
  { type: "listItem", text: "Managing access permissions" },
  { type: "listItem", text: "Removing access when appropriate" },
  { type: "listItem", text: "Monitoring authorized users" },
  { type: "paragraph", text: "SafeStop is intended for use by adults. Children are not intended to create or manage SafeStop accounts." },
  { type: "heading", text: "8. Location Services" },
  { type: "paragraph", text: "Certain SafeStop features require access to location services, including background location." },
  { type: "paragraph", text: "Location information may be unavailable, delayed, inaccurate, interrupted, or incomplete." },
  { type: "paragraph", text: "SafeStop does not guarantee location accuracy." },
  { type: "heading", text: "9. Photographs and Checkout Records" },
  { type: "paragraph", text: "Photographs uploaded through SafeStop are intended solely as user-generated checkout or session records." },
  { type: "paragraph", text: "SafeStop does not verify the authenticity, timing, accuracy, or completeness of uploaded photographs." },
  { type: "heading", text: "10. Third-Party Services" },
  { type: "paragraph", text: "SafeStop relies upon various third-party platforms, infrastructure providers, communication services, payment processors, advertising providers, location services, and other technology partners." },
  { type: "paragraph", text: "Examples may include Apple, Google, Supabase, Twilio, Stripe, AdMob, mapping providers, cloud hosting providers, analytics providers, and similar service providers." },
  { type: "paragraph", text: "These providers may change over time as our services evolve." },
  { type: "paragraph", text: "SafeStop is not responsible for outages, interruptions, failures, inaccuracies, billing issues, service disruptions, or other problems caused by third-party services." },
  { type: "heading", text: "11. Subscription and Billing Terms" },
  { type: "paragraph", text: "Certain SafeStop features may require a paid subscription." },
  { type: "paragraph", text: "Subscriptions are billed through Apple’s App Store using your Apple account." },
  { type: "paragraph", text: "Subscriptions automatically renew unless canceled through your Apple account settings before the renewal date." },
  { type: "paragraph", text: "Apple, not Ravenna Technologies LLC, manages billing, payment processing, cancellations, and refunds except where otherwise required by law." },
  { type: "paragraph", text: "Users are responsible for reviewing their subscription status and renewal settings." },
  { type: "paragraph", text: "Subscription pricing, features, and availability may change from time to time." },
  { type: "paragraph", text: "No refunds or partial refunds are provided by Ravenna Technologies LLC except where required by applicable law." },
  { type: "heading", text: "12. Disclaimer of Warranties" },
  { type: "paragraph", text: "SAFESTOP IS PROVIDED “AS IS” AND “AS AVAILABLE.”" },
  { type: "paragraph", text: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, RAVENNA TECHNOLOGIES LLC DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, RELIABILITY, AVAILABILITY, ACCURACY, AND SAFETY." },
  { type: "heading", text: "13. Assumption of Risk" },
  { type: "paragraph", text: "You understand and acknowledge that transportation and supervision of children involve inherent risks." },
  { type: "paragraph", text: "You voluntarily assume all risks arising from your use of SafeStop." },
  { type: "paragraph", text: "Responsibility for the safety, supervision, transportation, care, and wellbeing of children remains solely with the responsible adult at all times." },
  { type: "heading", text: "14. Limitation of Liability" },
  { type: "paragraph", text: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, RAVENNA TECHNOLOGIES LLC, ITS OWNERS, MEMBERS, EMPLOYEES, CONTRACTORS, AFFILIATES, LICENSORS, AND SERVICE PROVIDERS SHALL NOT BE LIABLE FOR ANY:" },
  { type: "listItem", text: "Injury" },
  { type: "listItem", text: "Death" },
  { type: "listItem", text: "Personal injury" },
  { type: "listItem", text: "Emotional distress" },
  { type: "listItem", text: "Loss of life" },
  { type: "listItem", text: "Property damage" },
  { type: "listItem", text: "Lost profits" },
  { type: "listItem", text: "Business interruption" },
  { type: "listItem", text: "Indirect damages" },
  { type: "listItem", text: "Consequential damages" },
  { type: "listItem", text: "Special damages" },
  { type: "listItem", text: "Punitive damages" },
  { type: "listItem", text: "Incidental damages" },
  { type: "paragraph", text: "arising from or related to:" },
  { type: "listItem", text: "Use of SafeStop" },
  { type: "listItem", text: "Inability to use SafeStop" },
  { type: "listItem", text: "Missed alerts" },
  { type: "listItem", text: "Delayed alerts" },
  { type: "listItem", text: "Failed alerts" },
  { type: "listItem", text: "Notification failures" },
  { type: "listItem", text: "GPS inaccuracies" },
  { type: "listItem", text: "User error" },
  { type: "listItem", text: "Device malfunction" },
  { type: "listItem", text: "Software bugs" },
  { type: "listItem", text: "System failures" },
  { type: "listItem", text: "Network outages" },
  { type: "listItem", text: "Third-party service failures" },
  { type: "listItem", text: "Any transportation-related incident" },
  { type: "paragraph", text: "This limitation applies even if Ravenna Technologies LLC has been advised of the possibility of such damages." },
  { type: "heading", text: "15. Maximum Liability Cap" },
  { type: "paragraph", text: "To the maximum extent permitted by law, the total aggregate liability of Ravenna Technologies LLC, its owners, officers, employees, contractors, affiliates, licensors, and service providers for any and all claims arising out of or relating to SafeStop shall not exceed the greater of:" },
  { type: "paragraph", text: "(a) One Hundred United States Dollars (US $100), or" },
  { type: "paragraph", text: "(b) The total amount paid by the user to SafeStop during the twelve (12) months immediately preceding the event giving rise to the claim." },
  { type: "paragraph", text: "This limitation applies regardless of the theory of liability asserted." },
  { type: "heading", text: "16. Release" },
  { type: "paragraph", text: "To the fullest extent permitted by law, you release and discharge Ravenna Technologies LLC from claims arising out of:" },
  { type: "listItem", text: "Child transportation incidents" },
  { type: "listItem", text: "Missed reminders" },
  { type: "listItem", text: "Missed alerts" },
  { type: "listItem", text: "Notification failures" },
  { type: "listItem", text: "Location inaccuracies" },
  { type: "listItem", text: "User actions or omissions" },
  { type: "listItem", text: "Any reliance on SafeStop" },
  { type: "heading", text: "17. Indemnification" },
  { type: "paragraph", text: "You agree to defend, indemnify, and hold harmless Ravenna Technologies LLC and its affiliates from any claims, damages, liabilities, losses, costs, and expenses arising from:" },
  { type: "listItem", text: "Your use of SafeStop" },
  { type: "listItem", text: "Your transportation or supervision of children" },
  { type: "listItem", text: "Your violation of these Terms" },
  { type: "listItem", text: "Your negligence or misconduct" },
  { type: "listItem", text: "Information you provide" },
  { type: "listItem", text: "Access you grant to other users" },
  { type: "heading", text: "18. Binding Arbitration Agreement" },
  { type: "paragraph", text: "PLEASE READ THIS SECTION CAREFULLY." },
  { type: "paragraph", text: "Except where prohibited by applicable law, any dispute, claim, or controversy arising out of or relating to SafeStop, these Terms, or the relationship between you and Ravenna Technologies LLC shall be resolved exclusively through binding arbitration." },
  { type: "paragraph", text: "Arbitration shall be conducted on an individual basis." },
  { type: "paragraph", text: "Neither party shall participate in:" },
  { type: "listItem", text: "Class actions" },
  { type: "listItem", text: "Class arbitrations" },
  { type: "listItem", text: "Representative actions" },
  { type: "listItem", text: "Private attorney general actions" },
  { type: "paragraph", text: "You waive any right to a jury trial." },
  { type: "paragraph", text: "You waive any right to participate as a plaintiff or class member in any purported class action proceeding." },
  { type: "paragraph", text: "If any portion of this arbitration provision is found unenforceable, the remaining provisions shall remain in full force and effect." },
  { type: "paragraph", text: "Arbitration shall take place in New Jersey and shall be governed by the Federal Arbitration Act." },
  { type: "heading", text: "19. Changes to SafeStop" },
  { type: "paragraph", text: "We may modify, suspend, or discontinue any portion of SafeStop at any time without notice." },
  { type: "heading", text: "20. Changes to These Terms" },
  { type: "paragraph", text: "We may update these Terms from time to time. Continued use of SafeStop after updates means you accept the updated Terms." },
  { type: "heading", text: "21. Governing Law" },
  { type: "paragraph", text: "These Terms shall be governed by the laws of the State of New Jersey, without regard to conflict of law principles." },
  { type: "heading", text: "22. Contact Information" },
  { type: "paragraph", text: "Ravenna Technologies LLC" },
  { type: "paragraph", text: "Email: yehuda@safestop.global" },
  { type: "paragraph", text: "Website: https://safestop.global" },
];

export default function TermsPage() {
  return (
    <LegalPage title="SafeStop Terms of Service" effectiveDate="Effective Date: June 22, 2026">
      <LegalDocument items={items} />
    </LegalPage>
  );
}
